
let body = document.body;
let loading = document.querySelector('.loading');
let home = document.querySelector('.home');
let office = document.querySelector('.office');
let media = document.querySelector('.media');
let hero = document.querySelector('.hero');
let animateTwo = document.querySelector('.animate-two');
let animateTwoText = document.querySelector('.animate-two__text');
let animateTwoImg = document.querySelector('.animate-two__img');
let t2 = document.querySelector('.t2');
let t3 = document.querySelector('.t3');
body.style.overflow = 'hidden';
home.style.marginTop = '115px';
setTimeout(() => loading.style.opacity = '1', 800);
setTimeout(() => home.style.marginTop = '0', 1200);
setTimeout(() => home.style.marginTop = '-115px', 1700);
setTimeout(() => home.style.marginTop = '-230px', 2200);
setTimeout(() => loading.style.opacity = '0', 2800);
setTimeout(() => hero.style.background = '#1B1C20', 3800);
setTimeout(() => loading.style.display = 'none', 3800);
setTimeout(() => animateTwo.style.display = 'flex', 3800);
setTimeout(() => animateTwo.style.opacity = '1', 4100);
setTimeout(() => t2.style.opacity = '1', 4800);
setTimeout(() => t3.style.opacity = '1', 5500);
setTimeout(() => animateTwoText.style.opacity = '0', 6000);
setTimeout(() => animateTwoText.style.display = 'none', 6500);
setTimeout(() => animateTwoImg.style.display = 'flex', 6500);
setTimeout(() => animateTwoImg.style.opacity = '1', 6700);
setTimeout(() => body.style.overflowY = 'auto', 6700);